=== autenticami/autenticami-authz/pkg/internal/iam/accessmanagement/data/acl-policy-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Version": {
      "type": "string"
    },
    "Label": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "Type": {
      "type": "string"
    },
    "Permit": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "Label": {
              "type": "string"
            },
            "Actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            },
            "Resources": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "Actions",
            "Resources"
          ]
        }
      ]
    },
    "Forbid": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "Label": {
              "type": "string"
            },
            "Actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                },
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            },
            "Resources": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "Actions",
            "Resources"
          ]
        }
      ]
    }
  },
  "required": [
    "Version",
    "Type",
    "Permit",
    "Forbid"
  ]
}

=== autenticami/autenticami-authz/pkg/internal/iam/accessmanagement/testdata/permissions-loader/validate-jsonschema/notvalid/2022-07-21/case1/input-policy-3.json
{
    "Version": "2022-07-21",
    "Label": "PeopleBaseReader",
    "Description": "This policy enable List and Read access to employee and timesheet of the domain people.",
    "Type": "ACL",
    "Permit": [
        {
            "Label": "permit-hr/person/reader/any",
            "Actions": [
                "people:ListEmployee",
                "people:ReadEmployee"
            ]
        },
        {
            "Label": "permit-hr/timesheet/writer/any",
            "Actions": [
                "people:ReadTimesheet",
                "people:CreateTimesheet",
                "people:UpdateTimesheet",
                "people:DeleteTimesheet"
            ],
            "Resources": [
                "uur:581616507495:default:hr-app:time-management:people/*"
            ]
        }
    ],
    "Forbid": []
}

=== autenticami/autenticami-authz/pkg/internal/iam/accessmanagement/testdata/permissions-loader/validate-jsonschema/valid/2022-07-21/case1/input-policy-5.json
{
    "Version": "2022-07-21",
    "Label": "PeopleBaseReader",
    "Description": "This policy enable List and Read access to employee and timesheet of the domain people.",
    "Type": "ACL",
    "Permit": [
        {
            "Actions": [
                "people:ListEmployee",
                "people:ReadEmployee"
            ],
            "Resources": [
                "uur:581616507495:default:hr-app:organisation:people/*"
            ]
        },
        {
            "Actions": [
                "people:ReadTimesheet",
                "people:CreateTimesheet",
                "people:UpdateTimesheet",
                "people:DeleteTimesheet"
            ],
            "Resources": [
                "uur:581616507495:default:hr-app:time-management:people/*"
            ]
        }
    ],
    "Forbid": [
        {
            "Actions": [
                "people:ListEmployee",
                "people:ReadEmployee"
            ],
            "Resources": []
        },
        {
            "Actions": [],
            "Resources": [
                "uur:581616507495:default:hr-app:organisation:people/*"
            ]
        }
    ]
}
